"""Generates mhm.nml for a single-domain calibration run."""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Dict, List, Tuple


def _lcover_block(scenes: List[Tuple[int, str]], last_year: int) -> str:
    lines = [f"  nLCoverScene = {len(scenes)}"]
    for i, (year, fname) in enumerate(scenes, start=1):
        end_y = scenes[i][0] - 1 if i < len(scenes) else last_year
        lines += [
            f"  LCoverYearStart({i}) = {year}",
            f"  LCoverYearEnd({i})   = {end_y}",
            f"  LCoverfName({i})     = '{fname}'",
        ]
    return "\n".join(lines)


def _gauge_block(gauges: List[Dict]) -> str:
    n = len(gauges)
    lines = [
        f"  nGaugesTotal       = {n}",
        f"  NoGauges_domain(1) = {n}",
    ]
    for j, g in enumerate(gauges, start=1):
        lines += [
            f"  Gauge_id(1,{j})       = {g['local_id']}",
            f"  gauge_filename(1,{j}) = \"{g['filename']}\"",
        ]
    return "\n".join(lines)


def _soil_depth_lines(depths: List[int]) -> str:
    return "\n".join(f"  soil_Depth({i + 1}) = {d}" for i, d in enumerate(depths))


def write_mhm_nml(
    out_path: Path,
    domain_dir: Path,
    *,
    resolution_hydrology: int,
    timestep: int,
    opti_method: int,
    opti_function: int,
    n_iterations: int,
    warming_days: int,
    eval_start: date,
    eval_end: date,
    lcover_scenes: List[Tuple[int, str]],
    gauges: List[Dict],
    n_soil_horizons: int,
    soil_depths: List[int],
) -> None:
    """Write a calibration-ready mhm.nml to out_path using absolute domain paths."""
    d = str(domain_dir)

    nml = f"""\
&project_description
  project_details="{domain_dir.name} calibration"
  setup_description="mHM calibration run assembled by mod18_calibrate_to_mhm"
  simulation_type="calibration"
  Conventions="CF-1.6"
  contact=""
  mHM_details="Helmholtz Center for Environmental Research - UFZ, Department Computational Hydrosystems"
  history="generated by mod18_calibrate_to_mhm"
/

&mainconfig
  iFlag_cordinate_sys = 0
  nDomains             = 1
  resolution_Hydrology(1) = {resolution_hydrology}
  L0Domain(1) = 1
  write_restart = .FALSE.
  read_opt_domain_data(1) = 0
/

&mainconfig_mhm_mrm
  mhm_file_RestartIn(1) = "{d}/restart/mHM_restart_001.nc"
  mrm_file_RestartIn(1) = "{d}/restart/mRM_restart_001.nc"
  resolution_Routing(1) = {resolution_hydrology}
  timestep = {timestep}
  read_restart  = .FALSE.
  mrm_read_river_network = .False.
  read_old_style_restart_bounds = .False.
  restart_reset_fluxes_states = .False.
  optimize = .TRUE.
  optimize_restart = .FALSE.
  opti_method   = {opti_method}
  opti_function = {opti_function}
/

&mainconfig_mrm
  ALMA_convention = .TRUE.
  varnametotalrunoff = 'total_runoff'
  filenametotalrunoff = 'total_runoff'
  gw_coupling = .false.
/

&config_riv_temp
  albedo_water = 0.15
  pt_a_water = 1.26
  emissivity_water = 0.96
  turb_heat_ex_coeff = 20.0
  max_iter = 50
  delta_iter = 1.0e-02
  step_iter = 5.0
  riv_widths_file = 'Q_bkfl'
  riv_widths_name = 'P_bkfl'
  dir_riv_widths(1) = "{d}/input/optional_data/"
/

&directories_general
  dirConfigOut         = "{d}/"
  dirCommonFiles       = "{d}/input/morph/"
  dir_Morpho(1)        = "{d}/input/morph/"
  dir_LCover(1)        = "{d}/input/luse/"
  mhm_file_RestartOut(1) = "{d}/restart/mHM_restart_001.nc"
  mrm_file_RestartOut(1) = "{d}/restart/mRM_restart_001.nc"
  dir_Out(1)           = "{d}/output/"
  file_LatLon(1)       = "{d}/input/latlon/latlon.nc"
/

&directories_mHM
  inputFormat_meteo_forcings = "nc"
  bound_error = .TRUE.
  dir_Precipitation(1) = "{d}/input/meteo/pre/"
  dir_Temperature(1)   = "{d}/input/meteo/tavg/"
  dir_ReferenceET(1)   = "{d}/input/meteo/pet/"
  dir_MinTemperature(1) = "{d}/input/meteo/"
  dir_MaxTemperature(1) = "{d}/input/meteo/"
  dir_NetRadiation(1)   = "{d}/input/meteo/"
  dir_absVapPressure(1) = "{d}/input/meteo/"
  dir_windspeed(1)      = "{d}/input/meteo/"
  dir_Radiation(1)      = "{d}/input/meteo/"
  time_step_model_inputs(1) = 0
/

&directories_mRM
  dir_Gauges(1)        = "{d}/input/gauge/"
  dir_Total_Runoff(1)  = "{d}/output/"
  dir_Bankfull_Runoff(1) = "{d}/input/optional_data/"
/

&optional_data
  dir_soil_moisture(1)      = "{d}/input/optional_data/"
  nSoilHorizons_sm_input    = 1
  timeStep_sm_input         = -2
  dir_neutrons(1)           = "{d}/input/optional_data/"
  dir_evapotranspiration(1) = "{d}/input/optional_data/"
  timeStep_et_input         = -2
  dir_tws(1)                = "{d}/input/optional_data/"
  timeStep_tws_input        = -2
  dir_spf(1)                = "{d}/input/optional_data/"
  timeStep_spf_input        = -1
  weight_for_optional_data  = 1
  snow_water_equivalent_threshold_for_spf = 0
/

&processSelection
  processCase(1)  = 1
  processCase(2)  = 1
  processCase(3)  = 1
  processCase(4)  = 1
  processCase(5)  = 0
  processCase(6)  = 1
  processCase(7)  = 1
  processCase(8)  = 3
  processCase(9)  = 1
  processCase(10) = 0
  processCase(11) = 0
/

&LCover
{_lcover_block(lcover_scenes, eval_end.year)}
/

&time_periods
  warming_Days(1)    = {warming_days}
  eval_Per(1)%yStart = {eval_start.year}
  eval_Per(1)%mStart = {eval_start.month:02d}
  eval_Per(1)%dStart = {eval_start.day:02d}
  eval_Per(1)%yEnd   = {eval_end.year}
  eval_Per(1)%mEnd   = {eval_end.month:02d}
  eval_Per(1)%dEnd   = {eval_end.day:02d}
/

&soildata
  iFlag_soilDB      = 0
  tillageDepth      = 200
  nSoilHorizons_mHM = {n_soil_horizons}
{_soil_depth_lines(soil_depths)}
/

&LAI_data_information
  timeStep_LAI_input      = -2
  inputFormat_gridded_LAI = "nc"
/

&LCover_MPR
  fracSealed_cityArea = 0.6
/

&directories_MPR
  dir_gridded_LAI(1) = "{d}/input/lai/"
/

&evaluation_gauges
{_gauge_block(gauges)}
/

&inflow_gauges
  nInflowGaugesTotal         = 0
  NoInflowGauges_domain(1)   = 0
  InflowGauge_id(1,1)        = -9
  InflowGauge_filename(1,1)  = ""
  InflowGauge_Headwater(1,1) = .FALSE.
/

&panEvapo
  evap_coeff = 1.30, 1.20, 0.72, 0.75, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.50
/

&nightDayRatio
  read_meteo_weights = .FALSE.
  fnight_prec  = 0.46, 0.50, 0.52, 0.51, 0.48, 0.50, 0.49, 0.48, 0.52, 0.56, 0.50, 0.47
  fnight_pet   = 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10, 0.10
  fnight_temp  = -0.76, -1.30, -1.88, -2.38, -2.72, -2.75, -2.74, -3.04, -2.44, -1.60, -0.94, -0.53
  fnight_ssrd  = 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
  fnight_strd  = 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45, 0.45
/

&Optimization
  nIterations = {n_iterations}
  seed        = -9
  dds_r       = 0.2
  sa_temp     = -9.0
  sce_ngs     = 2
  sce_npg     = -9
  sce_nps     = -9
  mcmc_opti   = .false.
  mcmc_error_params = 0.01, 0.6
/
"""
    out_path.write_text(nml)
